# -*- coding: utf-8 -*-
"""nightscout_push_synthetic.ipynb

Automatically generated by Colab.

"""

import hashlib
import math
import time
import requests
from datetime import datetime, timedelta, timezone

# ========= CONFIG =========
NIGHTSCOUT_URL = "https://<cgm-remote-monitor-NightScout-Dashboard-URL>/"
API_SECRET = "<NightScout API Secret>"  # plaintext, will be sha1 hashed for api-secret header
DEVICE_NAME = "GlucoseBuddy-Synthetic"

SEND_EVERY_SECONDS = 60
BASE_GLUCOSE = 120
# ==========================


def sha1(secret: str) -> str:
    return hashlib.sha1(secret.encode("utf-8")).hexdigest()


def glucose_at_step(step: int, base: float = 120.0) -> int:
    """
    synthetic glucose curve:
    - sine oscillation
    - some drift
    """
    g = base + 15 * math.sin(step / 18.0) + (step / 120.0)
    return int(round(g))


def post_one_sgv(glucose_mgdl: int, t: datetime) -> requests.Response:
    url = f"{NIGHTSCOUT_URL}/api/v1/entries.json"
    headers = {
        "Content-Type": "application/json",
        "api-secret": sha1(API_SECRET)
    }

    entry = {
        "type": "sgv",
        "sgv": int(glucose_mgdl),
        "date": int(t.timestamp() * 1000),
        "dateString": t.isoformat().replace("+00:00", "Z"),
        "device": DEVICE_NAME
    }

    # Nightscout accepts either a single object or an array; so send an array of 1.
    r = requests.post(url, json=[entry], headers=headers, timeout=30)
    r.raise_for_status()
    return r


if __name__ == "__main__":
    print("[LiveFeeder] Starting. Ctrl+C to stop.")
    step = 0

    try:
        while True:
            now = datetime.now(timezone.utc)
            g = glucose_at_step(step, BASE_GLUCOSE)

            r = post_one_sgv(g, now)

            # Nightscout usually returns inserted doc(s) with _id
            returned = r.json()
            _id = None
            if isinstance(returned, list) and len(returned) > 0 and isinstance(returned[0], dict):
                _id = returned[0].get("_id")

            print(f"[{now.isoformat().replace('+00:00','Z')}] SGV={g}  device={DEVICE_NAME}  id={_id}")
            step += 1
            time.sleep(SEND_EVERY_SECONDS)

    except KeyboardInterrupt:
        print("\n[LiveFeeder] Stopped.")